// Starting estimates for the calculator, not an engineering specification.
// Once saved in the settings page, database values take precedence.
export const SEED_ROOM_SETTINGS = {
  "ventilation": true,
  "rooms": [
    {
      "roomType": "Прихожая",
      "controls": {
        "p4": true,
        "p6": false,
        "p8": false,
        "scenarioSwitch": "none"
      },
      "relay": 2,
      "dimming": 0,
      "dali": 0,
      "led": 1,
      "radiators": 0,
      "waterFloor": 1,
      "electricFloor": 0,
      "fanCoil": 0,
      "co2": 0,
      "motion": 1,
      "wetZones": 0,
      "curtains": 0,
      "airConditioner": false
    },
    {
      "roomType": "Холл",
      "controls": {
        "p4": false,
        "p6": false,
        "p8": false,
        "scenarioSwitch": "none"
      },
      "relay": 2,
      "dimming": 0,
      "dali": 0,
      "led": 1,
      "radiators": 0,
      "waterFloor": 1,
      "electricFloor": 0,
      "fanCoil": 0,
      "co2": 0,
      "motion": 1,
      "wetZones": 0,
      "curtains": 1,
      "airConditioner": false
    },
    {
      "roomType": "Коридор",
      "controls": {
        "p4": true,
        "p6": false,
        "p8": false,
        "scenarioSwitch": "none"
      },
      "relay": 2,
      "dimming": 0,
      "dali": 0,
      "led": 1,
      "radiators": 0,
      "waterFloor": 0,
      "electricFloor": 0,
      "fanCoil": 0,
      "co2": 0,
      "motion": 1,
      "wetZones": 0,
      "curtains": 0,
      "airConditioner": false
    },
    {
      "roomType": "Лестница",
      "controls": {
        "p4": false,
        "p6": false,
        "p8": false,
        "scenarioSwitch": "none"
      },
      "relay": 2,
      "dimming": 0,
      "dali": 0,
      "led": 1,
      "radiators": 0,
      "waterFloor": 0,
      "electricFloor": 0,
      "fanCoil": 0,
      "co2": 0,
      "motion": 2,
      "wetZones": 0,
      "curtains": 0,
      "airConditioner": false
    },
    {
      "roomType": "Гостиная",
      "controls": {
        "p4": false,
        "p6": false,
        "p8": false,
        "scenarioSwitch": "4"
      },
      "relay": 3,
      "dimming": 1,
      "dali": 0,
      "led": 1,
      "radiators": 0,
      "waterFloor": 1,
      "electricFloor": 0,
      "fanCoil": 0,
      "co2": 1,
      "motion": 0,
      "wetZones": 0,
      "curtains": 2,
      "airConditioner": true
    },
    {
      "roomType": "Кухня",
      "controls": {
        "p4": false,
        "p6": false,
        "p8": false,
        "scenarioSwitch": "4"
      },
      "relay": 3,
      "dimming": 0,
      "dali": 0,
      "led": 1,
      "radiators": 0,
      "waterFloor": 1,
      "electricFloor": 0,
      "fanCoil": 0,
      "co2": 0,
      "motion": 1,
      "wetZones": 2,
      "curtains": 1,
      "airConditioner": false
    },
    {
      "roomType": "Кухня-гостиная",
      "controls": {
        "p4": false,
        "p6": false,
        "p8": false,
        "scenarioSwitch": "4"
      },
      "relay": 5,
      "dimming": 1,
      "dali": 0,
      "led": 2,
      "radiators": 0,
      "waterFloor": 2,
      "electricFloor": 0,
      "fanCoil": 0,
      "co2": 1,
      "motion": 1,
      "wetZones": 2,
      "curtains": 2,
      "airConditioner": true
    },
    {
      "roomType": "Столовая",
      "controls": {
        "p4": false,
        "p6": false,
        "p8": false,
        "scenarioSwitch": "4"
      },
      "relay": 2,
      "dimming": 1,
      "dali": 0,
      "led": 1,
      "radiators": 0,
      "waterFloor": 1,
      "electricFloor": 0,
      "fanCoil": 0,
      "co2": 1,
      "motion": 0,
      "wetZones": 0,
      "curtains": 1,
      "airConditioner": true
    },
    {
      "roomType": "Спальня",
      "controls": {
        "p4": false,
        "p6": false,
        "p8": false,
        "scenarioSwitch": "4"
      },
      "relay": 2,
      "dimming": 1,
      "dali": 0,
      "led": 1,
      "radiators": 1,
      "waterFloor": 0,
      "electricFloor": 0,
      "fanCoil": 0,
      "co2": 1,
      "motion": 0,
      "wetZones": 0,
      "curtains": 1,
      "airConditioner": true
    },
    {
      "roomType": "Детская",
      "controls": {
        "p4": false,
        "p6": false,
        "p8": false,
        "scenarioSwitch": "4"
      },
      "relay": 2,
      "dimming": 1,
      "dali": 0,
      "led": 1,
      "radiators": 1,
      "waterFloor": 0,
      "electricFloor": 0,
      "fanCoil": 0,
      "co2": 1,
      "motion": 0,
      "wetZones": 0,
      "curtains": 1,
      "airConditioner": true
    },
    {
      "roomType": "Гостевая спальня",
      "controls": {
        "p4": false,
        "p6": false,
        "p8": false,
        "scenarioSwitch": "4"
      },
      "relay": 2,
      "dimming": 1,
      "dali": 0,
      "led": 1,
      "radiators": 1,
      "waterFloor": 0,
      "electricFloor": 0,
      "fanCoil": 0,
      "co2": 1,
      "motion": 0,
      "wetZones": 0,
      "curtains": 1,
      "airConditioner": true
    },
    {
      "roomType": "Кабинет",
      "controls": {
        "p4": false,
        "p6": false,
        "p8": false,
        "scenarioSwitch": "none"
      },
      "relay": 2,
      "dimming": 1,
      "dali": 0,
      "led": 0,
      "radiators": 1,
      "waterFloor": 0,
      "electricFloor": 0,
      "fanCoil": 0,
      "co2": 1,
      "motion": 0,
      "wetZones": 0,
      "curtains": 1,
      "airConditioner": true
    },
    {
      "roomType": "Игровая",
      "controls": {
        "p4": false,
        "p6": false,
        "p8": false,
        "scenarioSwitch": "4"
      },
      "relay": 2,
      "dimming": 1,
      "dali": 0,
      "led": 1,
      "radiators": 0,
      "waterFloor": 1,
      "electricFloor": 0,
      "fanCoil": 0,
      "co2": 1,
      "motion": 0,
      "wetZones": 0,
      "curtains": 1,
      "airConditioner": true
    },
    {
      "roomType": "Гардеробная",
      "controls": {
        "p4": false,
        "p6": false,
        "p8": false,
        "scenarioSwitch": "none"
      },
      "relay": 1,
      "dimming": 0,
      "dali": 0,
      "led": 1,
      "radiators": 0,
      "waterFloor": 0,
      "electricFloor": 0,
      "fanCoil": 0,
      "co2": 0,
      "motion": 1,
      "wetZones": 0,
      "curtains": 0,
      "airConditioner": false
    },
    {
      "roomType": "Ванная комната",
      "controls": {
        "p4": false,
        "p6": false,
        "p8": false,
        "scenarioSwitch": "none"
      },
      "relay": 2,
      "dimming": 0,
      "dali": 0,
      "led": 1,
      "radiators": 0,
      "waterFloor": 1,
      "electricFloor": 0,
      "fanCoil": 0,
      "co2": 0,
      "motion": 1,
      "wetZones": 2,
      "curtains": 0,
      "airConditioner": false
    },
    {
      "roomType": "Санузел",
      "controls": {
        "p4": false,
        "p6": false,
        "p8": false,
        "scenarioSwitch": "none"
      },
      "relay": 2,
      "dimming": 0,
      "dali": 0,
      "led": 0,
      "radiators": 0,
      "waterFloor": 1,
      "electricFloor": 0,
      "fanCoil": 0,
      "co2": 0,
      "motion": 1,
      "wetZones": 1,
      "curtains": 0,
      "airConditioner": false
    },
    {
      "roomType": "Душевая",
      "controls": {
        "p4": false,
        "p6": false,
        "p8": false,
        "scenarioSwitch": "none"
      },
      "relay": 2,
      "dimming": 0,
      "dali": 0,
      "led": 1,
      "radiators": 0,
      "waterFloor": 1,
      "electricFloor": 0,
      "fanCoil": 0,
      "co2": 0,
      "motion": 1,
      "wetZones": 1,
      "curtains": 0,
      "airConditioner": false
    },
    {
      "roomType": "Постирочная",
      "controls": {
        "p4": false,
        "p6": false,
        "p8": false,
        "scenarioSwitch": "none"
      },
      "relay": 2,
      "dimming": 0,
      "dali": 0,
      "led": 0,
      "radiators": 0,
      "waterFloor": 1,
      "electricFloor": 0,
      "fanCoil": 0,
      "co2": 0,
      "motion": 1,
      "wetZones": 2,
      "curtains": 0,
      "airConditioner": false
    },
    {
      "roomType": "Кладовая",
      "controls": {
        "p4": false,
        "p6": false,
        "p8": false,
        "scenarioSwitch": "none"
      },
      "relay": 1,
      "dimming": 0,
      "dali": 0,
      "led": 0,
      "radiators": 0,
      "waterFloor": 0,
      "electricFloor": 0,
      "fanCoil": 0,
      "co2": 0,
      "motion": 1,
      "wetZones": 0,
      "curtains": 0,
      "airConditioner": false
    },
    {
      "roomType": "Котельная",
      "controls": {
        "p4": false,
        "p6": false,
        "p8": false,
        "scenarioSwitch": "none"
      },
      "relay": 2,
      "dimming": 0,
      "dali": 0,
      "led": 0,
      "radiators": 0,
      "waterFloor": 0,
      "electricFloor": 0,
      "fanCoil": 0,
      "co2": 0,
      "motion": 1,
      "wetZones": 2,
      "curtains": 0,
      "airConditioner": false
    },
    {
      "roomType": "Техническое помещение",
      "controls": {
        "p4": false,
        "p6": false,
        "p8": false,
        "scenarioSwitch": "none"
      },
      "relay": 2,
      "dimming": 0,
      "dali": 0,
      "led": 0,
      "radiators": 0,
      "waterFloor": 0,
      "electricFloor": 0,
      "fanCoil": 0,
      "co2": 0,
      "motion": 1,
      "wetZones": 1,
      "curtains": 0,
      "airConditioner": false
    },
    {
      "roomType": "Бассейн",
      "controls": {
        "p4": false,
        "p6": false,
        "p8": false,
        "scenarioSwitch": "4"
      },
      "relay": 4,
      "dimming": 1,
      "dali": 0,
      "led": 2,
      "radiators": 0,
      "waterFloor": 2,
      "electricFloor": 0,
      "fanCoil": 0,
      "co2": 1,
      "motion": 1,
      "wetZones": 2,
      "curtains": 0,
      "airConditioner": false
    },
    {
      "roomType": "Сауна",
      "controls": {
        "p4": false,
        "p6": false,
        "p8": false,
        "scenarioSwitch": "none"
      },
      "relay": 1,
      "dimming": 0,
      "dali": 0,
      "led": 1,
      "radiators": 0,
      "waterFloor": 0,
      "electricFloor": 0,
      "fanCoil": 0,
      "co2": 0,
      "motion": 0,
      "wetZones": 0,
      "curtains": 0,
      "airConditioner": false
    },
    {
      "roomType": "Хаммам",
      "controls": {
        "p4": false,
        "p6": false,
        "p8": false,
        "scenarioSwitch": "none"
      },
      "relay": 1,
      "dimming": 0,
      "dali": 0,
      "led": 1,
      "radiators": 0,
      "waterFloor": 0,
      "electricFloor": 0,
      "fanCoil": 0,
      "co2": 0,
      "motion": 0,
      "wetZones": 1,
      "curtains": 0,
      "airConditioner": false
    },
    {
      "roomType": "Спортивный зал",
      "controls": {
        "p4": false,
        "p6": false,
        "p8": false,
        "scenarioSwitch": "4"
      },
      "relay": 3,
      "dimming": 0,
      "dali": 0,
      "led": 1,
      "radiators": 0,
      "waterFloor": 1,
      "electricFloor": 0,
      "fanCoil": 0,
      "co2": 1,
      "motion": 0,
      "wetZones": 0,
      "curtains": 1,
      "airConditioner": true
    },
    {
      "roomType": "Домашний кинотеатр",
      "controls": {
        "p4": false,
        "p6": false,
        "p8": false,
        "scenarioSwitch": "4"
      },
      "relay": 2,
      "dimming": 2,
      "dali": 0,
      "led": 2,
      "radiators": 1,
      "waterFloor": 0,
      "electricFloor": 0,
      "fanCoil": 0,
      "co2": 1,
      "motion": 0,
      "wetZones": 0,
      "curtains": 1,
      "airConditioner": true
    },
    {
      "roomType": "Гараж",
      "controls": {
        "p4": false,
        "p6": false,
        "p8": false,
        "scenarioSwitch": "none"
      },
      "relay": 3,
      "dimming": 0,
      "dali": 0,
      "led": 0,
      "radiators": 1,
      "waterFloor": 0,
      "electricFloor": 0,
      "fanCoil": 0,
      "co2": 0,
      "motion": 1,
      "wetZones": 0,
      "curtains": 0,
      "airConditioner": false
    },
    {
      "roomType": "Мастерская",
      "controls": {
        "p4": false,
        "p6": false,
        "p8": false,
        "scenarioSwitch": "none"
      },
      "relay": 3,
      "dimming": 0,
      "dali": 0,
      "led": 0,
      "radiators": 1,
      "waterFloor": 0,
      "electricFloor": 0,
      "fanCoil": 0,
      "co2": 0,
      "motion": 1,
      "wetZones": 0,
      "curtains": 0,
      "airConditioner": false
    },
    {
      "roomType": "Терраса",
      "controls": {
        "p4": false,
        "p6": false,
        "p8": false,
        "scenarioSwitch": "none"
      },
      "relay": 2,
      "dimming": 0,
      "dali": 0,
      "led": 1,
      "radiators": 0,
      "waterFloor": 0,
      "electricFloor": 0,
      "fanCoil": 0,
      "co2": 0,
      "motion": 1,
      "wetZones": 0,
      "curtains": 0,
      "airConditioner": false
    },
    {
      "roomType": "Балкон или лоджия",
      "controls": {
        "p4": false,
        "p6": false,
        "p8": false,
        "scenarioSwitch": "none"
      },
      "relay": 1,
      "dimming": 0,
      "dali": 0,
      "led": 0,
      "radiators": 0,
      "waterFloor": 0,
      "electricFloor": 0,
      "fanCoil": 0,
      "co2": 0,
      "motion": 0,
      "wetZones": 0,
      "curtains": 0,
      "airConditioner": false
    }
  ]
} as const;
